import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"
import type { Metadata } from "next"
import "./styles/style.css";
import { CartProvider } from "@/context/carthandler/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
      <html lang="en">
        <head>
          <link href="https://api.fontshare.com/v2/css?f[]=clash-display@400&display=swap" rel="stylesheet" />
          <link href="https://api.fontshare.com/v2/css?f[]=satoshi@400&display=swap" rel="stylesheet"></link>
          <meta property="og:site_name" content="Furniro"></meta>
          <meta property="og:title" content="Furniture Ecommerce Marketplace"></meta>
          <meta property="og:description" content="Browse the Best Furniture in your Area without any Distractions." />
          <meta property="og:url" content="Visit the Best Furniture Marketplace"></meta>
        </head>
        <body>
          <SpeedInsights />
          <Analytics />
          {children}
        </body>
      </html>
    </CartProvider>
  );
}
